#!/usr/bin/env bash
# stolen from https://raw.github.com/mathiasbynens/dotfiles/master/.brew

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew tap josegonzalez/homebrew-php
brew install php55

# These two formulae didn’t work well last time I tried them:
brew install homebrew/dupes/vim
brew install homebrew/dupes/screen

# Install other useful binaries
brew install ack
brew install git
brew install imagemagick
brew install node
brew install tree

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
	brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask macvim
installcask sublime-text
installcask tor-browser
installcask transmission
installcask vlc

# Remove outdated versions from the cellar
brew cleanup
